### ISSUE TITLE
KLB reader fails to detect one of the submitted filesets

### ISSUE THREAD

**Issue by sbesson** [IDR/idr0044-mcdole-tardislightsheet#1]
Tried to import the four submitted datasets described in `experimentA/idr0044-experimentA-filePaths.tsv` with

```
bin/omero import -f --bulk idr0044-mcdole/experimentA/idr0044-experimentA-bulk.yml
```

using a version of Bio-Formats containing https://github.com/openmicroscopy/bioformats/pull/3219.

The three first datasets are correctly detected with all files corresponding to the individual timepoints and orthogonal projections grouped together. For the last dataset, however the `setId` call failed with

```
2018-10-02 16:11:41,764 55905      [      main] ERROR     ome.formats.importer.cli.ErrorHandler - FILE_EXCEPTION: /uod/idr/filesets/idr0044-mcdole/20180926-ftp/160723/Mmu_E1_GFPLifeactxmKate2nls.TM000154_timeFused_blending/SPM00_TM000154_CM00_CM01_CHN01.fusedStack_xyProjection.corrected.shifted.klb
java.lang.IllegalArgumentException: 0 must be non-null and strictly positive.
java.lang.IllegalArgumentException: 0 must be non-null and strictly positive.
	at ome.xml.model.primitives.PositiveInteger.<init>(PositiveInteger.java:48) ~[ome-xml.jar:5.6.4-SNAPSHOT]
	at loci.formats.MetadataTools.populatePixelsOnly(MetadataTools.java:310) ~[formats-api.jar:6.0.0-SNAPSHOT]
	at loci.formats.MetadataTools.populateMetadata(MetadataTools.java:262) ~[formats-api.jar:6.0.0-SNAPSHOT]
	at loci.formats.MetadataTools.populatePixels(MetadataTools.java:151) ~[formats-api.jar:6.0.0-SNAPSHOT]
	at loci.formats.MetadataTools.populatePixels(MetadataTools.java:97) ~[formats-api.jar:6.0.0-SNAPSHOT]
	at loci.formats.in.KLBReader.initFile(KLBReader.java:390) ~[formats-gpl.jar:6.0.0-SNAPSHOT]
	at loci.formats.FormatReader.setId(FormatReader.java:1395) ~[formats-api.jar:6.0.0-SNAPSHOT]
	at loci.formats.ImageReader.setId(ImageReader.java:842) ~[formats-api.jar:6.0.0-SNAPSHOT]
	at loci.formats.ReaderWrapper.setId(ReaderWrapper.java:650) ~[formats-api.jar:6.0.0-SNAPSHOT]
	at loci.formats.ChannelFiller.setId(ChannelFiller.java:223) ~[formats-bsd.jar:6.0.0-SNAPSHOT]
	at loci.formats.ReaderWrapper.setId(ReaderWrapper.java:650) ~[formats-api.jar:6.0.0-SNAPSHOT]
	at loci.formats.ChannelSeparator.setId(ChannelSeparator.java:291) ~[formats-bsd.jar:6.0.0-SNAPSHOT]
	at loci.formats.ReaderWrapper.setId(ReaderWrapper.java:650) ~[formats-api.jar:6.0.0-SNAPSHOT]
	at loci.formats.Memoizer.setId(Memoizer.java:662) ~[formats-bsd.jar:6.0.0-SNAPSHOT]
	at loci.formats.ReaderWrapper.setId(ReaderWrapper.java:650) ~[formats-api.jar:6.0.0-SNAPSHOT]
	at ome.formats.importer.ImportCandidates.singleFile(ImportCandidates.java:427) [blitz.jar:na]
	at ome.formats.importer.ImportCandidates.handleFile(ImportCandidates.java:576) [blitz.jar:na]
	at org.apache.commons.io.DirectoryWalker.walk(DirectoryWalker.java:367) [commons-io.jar:1.4]
	at org.apache.commons.io.DirectoryWalker.walk(DirectoryWalker.java:364) [commons-io.jar:1.4]
	at org.apache.commons.io.DirectoryWalker.walk(DirectoryWalker.java:335) [commons-io.jar:1.4]
	at ome.formats.importer.ImportCandidates.execute(ImportCandidates.java:381) [blitz.jar:na]
	at ome.formats.importer.ImportCandidates.<init>(ImportCandidates.java:222) [blitz.jar:na]
	at ome.formats.importer.ImportCandidates.<init>(ImportCandidates.java:174) [blitz.jar:na]
	at ome.formats.importer.cli.CommandLineImporter.<init>(CommandLineImporter.java:148) [blitz.jar:na]
	at ome.formats.importer.cli.CommandLineImporter.main(CommandLineImporter.java:991) [blitz.jar:na]
```

**Comment by dgault** [comment]
This seems to be due to the channel index on this fileset is 1, with no channel 0. The previous dataset was 0 indexed. So I don't know if we handle any possible indexing or not

**Comment by sbesson** [comment]
Ah interesting, I hadn't realized that. It seems to match what we have on disk i.e.

```
[sbesson@idr0-slot3 160723]$ ls ../160723/Mmu_E1_GFPLifeactxmKate2nls.TM000000_timeFused_blending/
SPM00_TM000000_CM00_CM01_CHN01.fusedStack.corrected.shifted.klb
SPM00_TM000000_CM00_CM01_CHN01.fusedStack_xyProjection.corrected.shifted.klb
SPM00_TM000000_CM00_CM01_CHN01.fusedStack_xzProjection.corrected.shifted.klb
SPM00_TM000000_CM00_CM01_CHN01.fusedStack_yzProjection.corrected.shifted.klb
```

vs

```
[sbesson@idr0-slot3 160723]$ ls ../151205/Mmu_E1_mKate2.TM000000_timeFused_blending/
SPM00_TM000000_CM00_CM01_CHN00.fusedStack.corrected.shifted.klb
SPM00_TM000000_CM00_CM01_CHN00.fusedStack_xyProjection.corrected.shifted.klb
SPM00_TM000000_CM00_CM01_CHN00.fusedStack_xzProjection.corrected.shifted.klb
SPM00_TM000000_CM00_CM01_CHN00.fusedStack_yzProjection.corrected.shifted.klb
```

Is each individual KLB file effectively detected as a single-channel image?

To some extent the question in https://github.com/IDR/idr0044-mcdole/issues/1#issuecomment-427369903 brings us back to the question discussed a few days ago i.e. would it help to separate the reading of individual KLB files following the specification from the logic that navigates the tree? Would a pattern file be sufficient to cover all use cases for these datasets?

**Comment by sbesson** [comment]
Should be addressed by https://github.com/openmicroscopy/bioformats/pull/3256. Closing as this will be tested in `test60`
